# -*- coding: utf-8 -*-
"""Sentiment_Analysis(Iphone17).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mw3oXOS7hMfOVJbMZiIGF8UZ-VxQmWCS
"""

# 1. Install the necessary libraries

!pip install transformers torch pandas tqdm --quiet


# 2. Import the necessary modules

import pandas as pd
from transformers import pipeline
from tqdm.notebook import tqdm


# 3. Upload the CSV file

df = pd.read_csv("reddit_iphone17_comments.csv.csv")

# If the column name is different, check:
print(df.columns)

# For example, we will use the ‘comment_body’ column:
df = df.dropna(subset=['comment_body'])  # boş değerleri temizle
df['comment_body'] = df['comment_body'].astype(str)

print(f"Toplam yorum sayısı: {len(df)}")


#  4. Load the sentiment analysis model

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english",
    truncation=True,
    batch_size=32,
    device=0
)


# 5. Analyze comments in batches

batch_size = 100
results = []

for i in tqdm(range(0, len(df), batch_size), desc="Sentiment analysis progress"):
    batch = df['comment_body'][i:i+batch_size].tolist()
    try:
        batch_results = sentiment_pipeline(batch)
        results.extend(batch_results)
    except Exception as e:
        print(f"Batch {i}-{i+batch_size} Error: {e}")


# 6. Add the results to the DataFrame

df['sentiment_label'] = [r['label'] for r in results]
df['sentiment_score'] = [r['score'] for r in results]


#  7. Save the results

output_path = "reddit_sentiment_results.csv"
df.to_csv(output_path, index=False)
print(f"Sentiment analysis completed! Results: {output_path}")


# 📊 8. View sample output

df.head(10)

print(" Most positive review:")
print(df.loc[df['sentiment_score'].idxmax(), 'comment_body'])
print("\n Most negative review:")
print(df.loc[df['sentiment_score'].idxmin(), 'comment_body'])

df['sentiment_label'].value_counts(normalize=True).plot(kind='bar')

from collections import Counter
from nltk.corpus import stopwords
import re
import nltk

nltk.download('stopwords')

stop = set(stopwords.words('english'))
words = []
for text in df['comment_body']:
    words += [w.lower() for w in re.findall(r'\b\w+\b', text) if w.lower() not in stop]
Counter(words).most_common(20)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,4))
sns.countplot(data=df, x='sentiment_label', palette='coolwarm')
plt.title('Sentiment Distribution in Reddit Comments (iPhone 17)')
plt.xlabel('Emotion Type')
plt.ylabel('Number of Comments')
plt.show()

from wordcloud import WordCloud
import nltk, re
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = re.sub(r'http\S+|www\S+|[^A-Za-z\s]', '', str(text))
    words = [word.lower() for word in text.split() if word.lower() not in stop_words]
    return ' '.join(words)

# Pozitif ve negatif yorumları ayır
positive_text = ' '.join(df[df['sentiment_label'] == 'POSITIVE']['comment_body'].apply(clean_text))
negative_text = ' '.join(df[df['sentiment_label'] == 'NEGATIVE']['comment_body'].apply(clean_text))

# WordCloud oluştur
plt.figure(figsize=(12,6))
plt.subplot(1,2,1)
plt.imshow(WordCloud(width=600, height=400, background_color='white').generate(positive_text))
plt.title('Words Most Frequently Used in Positive Reviews')
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(WordCloud(width=600, height=400, background_color='black', colormap='Reds').generate(negative_text))
plt.title('Words Most Frequently Used in Negative Reviews')
plt.axis('off')
plt.show()

from collections import Counter

def get_top_words(text_series, n=20):
    words = []
    for text in text_series:
        words += clean_text(text).split()
    return Counter(words).most_common(n)

print("Words Most Frequently Used in Positive Reviews:")
print(get_top_words(df[df['sentiment_label']=='POSITIVE']['comment_body']))

print("\nWords Most Frequently Used in Negative Reviews:")
print(get_top_words(df[df['sentiment_label']=='NEGATIVE']['comment_body']))

top_comments = df.sort_values(by='comment_score', ascending=False).head(10)[['comment_body','sentiment_label','comment_score']]
top_comments

